# Generated by Django 3.1.7 on 2021-03-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210317_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='customer',
        ),
    ]
